export const gamedata = [
  {
    category: "RPG",
    name: "gta",
    title: "Grand Theft Auto V",
    publisher: "Rockstar Games",
    home_desc:
      "When a young street hustler, a retired bank robber and a terrifying psychopath find themselves entangled with some of the most frightening and deranged elements of the criminal underworld, the U.S. government and the entertainment industry, they must pull off a series of dangerous heists to survive in a ruthless city in which they can trust nobody, least of all each other.",
    description: [
      "The sprawling sun-soaked metropolis of Los Santos is chock full of self-help coaches, starlets and C-List celebrities, once on top of the media world, now struggling to stay relevant in time of economic malaise and lowest-common-denominator reality TV. Amidst this madness, three unique criminals plan their own chances of survival and success: Franklin, a street-level hustler in search of opportunities for serious money; Michael, an ex-con whose ",
      "retirement",
      " is a less rosy than he hoped it would be; and Trevor, a violent dude driven by the chance for a quick high and the next big score. Nearly out of options, the crew risks it all in a series of daring and dangerous heists that could set them up for life - one way or the other.",
    ],
    info: [
      <h4>Platform: </h4>,
      "PC, PS, XBOX",
      <h4>Release Date: </h4>,
      "18 November 2014",
      <h4>Developer: </h4>,
      "Rockstar North",
      <h4>Genre(s): </h4>,
      "Action Adventure, Modern, Open-World",
      <h4># of players: </h4>,
      "Up to 30",
      <h4>Rating: </h4>,
      "M",
    ],
  },
  {
    category: "RPG",
    name: "witcher",
    title: "Witcher 3",
    publisher: "Warner Bros",
    description: [
      "With the Empire attacking the Kingdoms of the North and the Wild Hunt, a cavalcade of ghastly riders, breathing down your neck, the only way to survive is to fight back. As Geralt of Rivia, a master swordsman and monster hunter, leave none of your enemies standing. Explore a gigantic open world, slay beasts and decide the fates of whole communities with your actions, all in a genuine next generation format.",
    ],
    info: [
      <h4>Platform: </h4>,
      "PC, PS, XBOX",
      <h4>Release Date: </h4>,
      "18 May 2018",
      <h4>Developer: </h4>,
      "CD Project Red",
      <h4>Genre(s): </h4>,
      "Action RPG, Role-Playing",
      <h4># of players: </h4>,
      "Single Player",
      <h4>Rating: </h4>,
      "M",
    ],
  },
  {
    category: "RPG",
    name: "mafia",
    title: "Mafia 3",
    publisher: "2K Games",
    description: [
      "After taking a bullet during World War II and returning home to Empire Bay on leave, Sicilian immigrant Vito Scaletta discovers that his late father was indebted to a loan shark. He needs to make a lot of money fast, and thanks to his career criminal best friend Joe, soon becomes entangled with the mob. As Vito, you need to prove yourself by committing crimes of escalating reward, status, and consequence. But what happens when your motivations become less about necessity and more about greed? When having it all is not enough? For the first time ever, Mafia II: Definitive Edition packs the entire Mafia II crime drama into one HD package. HDR and 4K resolution are supported on PC as well as on PlayStation®4 Pro and Xbox One X consoles. Mafia II: Definitive Edition also benefits from improved facial animations to give cutscenes an even more cinematic feel. While technological and graphical improvements have given Empire Bay and its inhabitants a visual overhaul, Vito's timeless story is unchanged",
    ],
    info: [
      <h4>Platform: </h4>,
      "PC, PS, XBOX",
      <h4>Release Date: </h4>,
      "19 May 2020",
      <h4>Developer: </h4>,
      "Hangar 13",
      <h4>Genre(s): </h4>,
      "Action, Adventure, Open-World",
      <h4># of players: </h4>,
      "Singleplayer",
      <h4>Rating: </h4>,
      "M",
    ],
  },
  {
    category: "FPS",
    name: "Rainbow",
    title: "Rainbow Six Siege",
    publisher: "Ubisoft",
    description: [
      <h5>Description: </h5>,
      "Tom Clancy's Rainbow Six Siege is the upcoming installment of the acclaimed first-person shooter franchise developed by the renowned Ubisoft Montreal studio.       ",
      "Inspired by the reality of counter terrorist operatives across the world, Tom Clancy's Rainbow Six Siege invites players to master the art of destruction. Intense close quarters confrontations, high lethality, tactics, team play, and explosive action are at the center of the experience. ",
      "The gameplay of Tom Clancy's Rainbow Six Siege sets a new bar for intense firefights and expert strategy in the rich legacy of past Tom Clancy's Rainbow Six games.",
    ],
    info: [
      <h4>Platform: </h4>,
      "PC, PS, XBOX",
      <h4>Release Date: </h4>,
      "1 December 2015",
      <h4>Developer: </h4>,
      "Ubisoft, Montreal",
      <h4>Genre(s): </h4>,
      "Modern, Action, Shooter, First-Person, Tactical",
      <h4># of players: </h4>,
      "Up to 10",
      <h4>Rating: </h4>,
      "M",
    ],
  },
  {
    category: "FPS",
    name: "cs",
    title: "Counter Strike: Global Offensive",
    publisher: "Valve",
    description: [
      <h5>Description: </h5>,
      "Counter-Strike: Global Offensive (CS: GO) expands upon the team-based action gameplay that it pioneered when it was launched 19 years ago.",
      "CS: GO features new maps, characters, weapons, and game modes, and delivers updated versions of the classic CS content (de_dust2, etc.)",
      "Counter-Strike took the gaming industry by surprise when the unlikely MOD became the most played online PC action game in the world almost immediately after its release in August 1999,",
      "said Doug Lombardi at Valve. ",
      "For the past 12 years, it has continued to be one of the most-played games in the world, headline competitive gaming tournaments and selling over 25 million units worldwide across the franchise. CS: GO promises to expand on CS' award-winning gameplay and deliver it to gamers on the PC as well as the next gen consoles and the Mac.",
    ],
    info: [
      <h4>Platform: </h4>,
      "PC",
      <h4>Release Date: </h4>,
      "21 August 2012",
      <h4>Developer: </h4>,
      "Valve Software, Hidden Path Entertainment",
      <h4>Genre(s): </h4>,
      "Action, Shooter, First-Person, Modern, Tactical, Modern",
      <h4># of players: </h4>,
      "Up to 10",
      <h4>Rating: </h4>,
      "M",
    ],
  },
  {
    category: "FPS",
    name: "coldwar",
    title: "Call of Duty: Cold War",
    publisher: "Activision",
    description: [
      "The iconic Black Ops series is back with Call of Duty: Black Ops Cold War - the direct sequel to the original and fan-favorite Call of Duty: Black Ops. ",
      "Black Ops Cold War will drop fans into the depths of the Cold War’s volatile geopolitical battle of the early 1980s. Nothing is ever as it seems in a gripping single-player Campaign, where players will come face-to-face with historical figures and hard truths, as they battle around the globe through iconic locales like East Berlin, Vietnam, Turkey, Soviet KGB headquarters and more.",
      "As elite operatives, you will follow the trail of a shadowy figure named Perseus who is on a mission to destabilize the global balance of power and change the course of history. Descend into the dark center of this global conspiracy alongside iconic characters Woods, Mason and Hudson and a new cast of operatives attempting to stop a plot decades in the making.",
      "Beyond the Campaign, players will bring a Cold War arsenal of weapons and equipment into the next generation of Multiplayer and Zombies experiences.",
    ],
    info: [
      <h4>Platform: </h4>,
      "PC, PS, XBOX",
      <h4>Release Date: </h4>,
      "13 November 2020",
      <h4>Developer: </h4>,
      "Treyarch, Beenox",
      <h4>Genre(s): </h4>,
      "Action, Shooter, First-Person, Tactical",
      <h4># of players: </h4>,
      "Up to 40",
      <h4>Rating: </h4>,
      "M",
    ],
  },
  {
    category: "Sports",
    name: "nba",
    title: "NBA 2K21",
    publisher: "2K Games",
    description: [
      "With extensive improvements upon its best-in-class graphics and gameplay, competitive and community online features, and deep, varied game modes, NBA 2K21 offers one-of-a-kind immersion into all facets of NBA basketball and culture - where Everything is Game.",
    ],
    info: [
      <h4>Platform: </h4>,
      "PC, PS, XBOX",
      <h4>Release Date: </h4>,
      "04 September 2020",
      <h4>Developer: </h4>,
      "Visual Concepts",
      <h4>Genre(s): </h4>,
      "Sports, Team, Basketball, Arcade",
      <h4># of players: </h4>,
      "Up to 10",
      <h4>Rating: </h4>,
      "E",
    ],
  },
  {
    category: "Sports",
    name: "fifa",
    title: "FIFA 2021",
    publisher: "Electronic Arts",
    description: [
      "Win as one in EA SPORTS FIFA 21 with new ways to team up and express yourself on the street and in the stadium. Powered by Frostbite, FIFA 21 raises the game with fresh features:",
      "Enjoy even bigger victories together in VOLTA FOOTBALL SQUADS and FIFA Ultimate Team™ Co-Op.",
      "Feel a new level of gameplay realism that rewards you for your creativity and control.",
      "Manage every moment in FIFA 21 Career Mode with new innovations that create additional depth in matches, transfers and training.",
      "Experience unrivaled authenticity that gives you the most true-to-life experience of The World’s Game including the UEFA Champions League and CONMEBOL Libertadores.",
    ],
    info: [
      <h4>Platform: </h4>,
      "PC, PS, XBOX",
      <h4>Release Date: </h4>,
      "09 October 2020",
      <h4>Developer: </h4>,
      "EA Canada",
      <h4>Genre(s): </h4>,
      "Sports, Team, Soccer, Sim",
      <h4># of players: </h4>,
      "Up to 22",
      <h4>Rating: </h4>,
      "E",
    ],
  },
  {
    category: "Sports",
    name: "nfl",
    title: "Madden NFL 2O21",
    publisher: "Electronic Arts",
    description: [
      "Innovative new gameplay mechanics in Madden NFL 21 deliver advanced levels of control and inspire creativity. Get crafty with the all-new Skill Stick that allows for enhanced precision on both sides of the ball. Push the limits of your legacy in Face of the Franchise: Rise To Fame. The new playable documentary career mode offers all-out levels of agency and depth throughout your journey to the Hall of Fame. Pull up for a brand-new season of Ultimate Team content as you earn rewards to finesse your depth chart and flex your fantasy roster on the competition. Your favorite NFL teams’ playbooks are updated in Play Now and Franchise based on new schemes and new plays utilized during the real-life NFL season.",
    ],
    info: [
      <h4>Platform: </h4>,
      "PC, PS, XBOX",
      <h4>Release Date: </h4>,
      "25 August 2020",
      <h4>Developer: </h4>,
      "EA Sports",
      <h4>Genre(s): </h4>,
      "Sports, Team, Football, Sim",
      <h4># of players: </h4>,
      "Up to 6",
      <h4>Rating: </h4>,
      "E",
    ],
  },
  {
    category: "VR",
    name: "alyx",
    title: "Half Life : Alyx",
    publisher: "Valve Software",
    description: [
      "Half-Life: Alyx is Valve's VR return to the Half-Life series. It's the story of an impossible fight against a vicious alien race known as the Combine, set between the events of Half-Life and Half-Life 2. Playing as Alyx Vance, you are humanity's only chance for survival. The Combine's control of the planet since the Black Mesa incident has only strengthened as they corral the remaining population in cities. Among them are some of Earth's greatest scientists: you and your father, Dr. Eli Vance. As founders of a fledgling resistance, you've continued your clandestine scientific activityperforming critical research, and building invaluable tools for the few humans brave enough to defy the Combine. Every day, you learn more about your enemy, and every day you work toward finding a weakness.",
    ],
    info: [
      <h4>Platform: </h4>,
      "PC",
      <h4>Release Date: </h4>,
      "23 March 2020",
      <h4>Developer: </h4>,
      "Valve Software",
      <h4>Genre(s): </h4>,
      "Action, First-Person, Shooter, Arcade, VR",
      <h4># of players: </h4>,
      "Singleplayer",
      <h4>Rating: </h4>,
      "M",
    ],
  },
  {
    category: "VR",
    name: "hot",
    title: "SUPERHOT",
    publisher: "SUPERHOT",
    description: [
      "SUPERHOT is the first person shooter where time moves only when you move. With its gameplay and unique, stylized graphics SUPERHOT aims to finally add something new and disruptive to the FPS genre. See the bullets crawling towards you as you carefully plan your steps and aim your gun. Enjoy the mayhem that is unleashed as you put that plan into motion. Dodge bullets. Take out your enemies. One step at a time.",
    ],
    info: [
      <h4>Platform: </h4>,
      "PC, XBOX, PS",
      <h4>Release Date: </h4>,
      "25 February 2016",
      <h4>Developer: </h4>,
      "SUPERHOT",
      <h4>Genre(s): </h4>,
      "Modern, Action, First-Person, Shooter, Tactical, VR",
      <h4># of players: </h4>,
      "Singleplayer",
      <h4>Rating: </h4>,
      "T",
    ],
  },
  {
    category: "VR",
    name: "saber",
    title: "Beat Saber",
    publisher: "Hyperbolic Magnetism",
    description: [
      "Beat Saber is a VR rhythm game where your goal is to slash the beats which perfectly fit into precisely handcrafted music.",
    ],
    info: [
      <h4>Platform: </h4>,
      "PC, PS",
      <h4>Release Date: </h4>,
      "21 May 2019",
      <h4>Developer: </h4>,
      "Hyperbolic Magnetism",
      <h4>Genre(s): </h4>,
      "Action, General, VR",
      <h4># of players: </h4>,
      "Singleplayer",
      <h4>Rating: </h4>,
      "E",
    ],
  },
  {
    category: "Strategy",
    name: "ageof",
    title: "Age of Empires : Definitive Edition",
    publisher: "Microsoft Game Studios",
    description: [
      "Age of Empires is an epic real-time strategy game spanning 10,000 years, in which players are the guiding spirit in the evolution of small stone age tribes. Starting with minimal resources, players are challenged to build their tribes into great civilizations. Gamers can choose from one of several ways to win the game, including: world domination by conquering enemy civilizations, exploration of the known world and economic victory through the accumulation of wealth. Age of Empires was developed by Ensemble Studios and features the expertise of Bruce Shelley, co-designer of the hit strategy game Civilization. In 1997, Age of Empires changed RTS games forever. Today, twenty years later, Age of Empires: Definitive Edition begins that transformation anew with all-new graphics, remastered sound and music, and a smooth UI experience rebuilt from the ground up.",
    ],
    info: [
      <h4>Platform: </h4>,
      "PC",
      <h4>Release Date: </h4>,
      "20 February 2018",
      <h4>Developer: </h4>,
      "Microsoft Game Studios",
      <h4>Genre(s): </h4>,
      "Strategy, Real-Time, Command, Historic",
      <h4># of players: </h4>,
      "Up to 8",
      <h4>Rating: </h4>,
      "T",
    ],
  },
  {
    category: "Strategy",
    name: "company",
    title: "Company Of Heroes 2",
    publisher: "Sega",
    description: [
      "It is 1941 and the beginning of what will become the most brutal conflict of World War II, as Germany launches a full-scale invasion of the frozen tundra of the Soviet Union which would result in over 14 million military casualties. Take command of the iconic Soviet Red Army in brutal frontline warfare to free Mother Russia from the invading Nazis. Your strategic skills and tactical expertise hold the power to tip the very balance of this conflict in the sequel to the critically acclaimed and multi award-winning Company of Heroes. Engage in visceral tactical combat that will define you as a military leader and challenge you to wield the might of the Soviet Empire as you smash your way to Berlin.",
    ],
    info: [
      <h4>Platform: </h4>,
      "PC",
      <h4>Release Date: </h4>,
      "25 June 2013",
      <h4>Developer: </h4>,
      "Relic",
      <h4>Genre(s): </h4>,
      "Strategy, Real-Time, Command, Historic, General",
      <h4># of players: </h4>,
      "Up to 8",
      <h4>Rating: </h4>,
      "M",
    ],
  },
  {
    category: "Strategy",
    name: "totalwar",
    title: "Total War : Rome II",
    publisher: "Sega",
    description: [
      "Become the world’s first superpower and command the most incredible and vast war machine of the Ancient world. Dominate the enemies of your glorious empire by military, economic and political means. Your ascendency will yield admiration from your followers but will also attract greed and jealousy, even from your closest allies. Will betrayal strike you down, or will you be the first to turn on old friends? How much are you ready to sacrifice for your vision of Rome? Will you fight to save the Republic, or plot to rule alone as Dictator — as Emperor? Total War: Rome 2.",
    ],
    info: [
      <h4>Platform: </h4>,
      "PC",
      <h4>Release Date: </h4>,
      "3 September 2013",
      <h4>Developer: </h4>,
      "Creative Assembly",
      <h4>Genre(s): </h4>,
      "Strategy, Real-Time, Command, Historic, General",
      <h4># of players: </h4>,
      "Up to 4",
      <h4>Rating: </h4>,
      "T",
    ],
  },
  {
    category: "Indie",
    name: "little",
    title: "Little Nightmares II",
    publisher: "Bandai Namco Games",
    description: [
      "Little Nightmares II is a suspense-adventure game in which you play as Mono, a young boy trapped in a world that has been distorted by a mysterious transmission from a distant signal tower. With Six, the girl in a yellow raincoat, Mono sets out to discover the dark secrets of The Signal Tower and save Six from her terrible fate; but their journey will not be easy as Mono and Six will face an array of new threats from the terrible residents of this world. Will you dare face this collection of new, little nightmares? PLAY A DARK, THRILLING, SUSPENSE ADVENTURE: A host of brand-new residents lie in wait to haunt your steps and disturb your sleep. Outsmart the sadistic teacher, survive the bloodthirsty hunter and flee from many more terrifying characters, as Mono and Six journey through this world together. DISCOVER A FANTASTICAL WORLD CORRUPTED BY THE SIGNAL TOWER: Escape a world that’s rotten from the inside. Your journey will take you from creepy woodlands to sinister schools on your way to the dreadful Signal Tower. Find the source of the evil that spreads through the TV screens of the world. AWAKEN YOUR INNER CHILD TO SAVE SIX FROM THE DARKNESS: Six is fading from this world, and her only hope is to journey with Mono to find what has afflicted her from the Signal Tower. In this world of unknown terrors, you are her only beacon of hope. Can you gather up the courage to fend off your tormenters, and work with Six to make sense of The Signal Tower?",
    ],
    info: [
      <h4>Platform: </h4>,
      "PC, PS, XBOX, Switch, Stadia",
      <h4>Release Date: </h4>,
      "11 February 2021",
      <h4>Developer: </h4>,
      "Tarsier Studios",
      <h4>Genre(s): </h4>,
      "Action Adventure, Linear",
      <h4># of players: </h4>,
      "Singleplayer",
      <h4>Rating: </h4>,
      "T",
    ],
  },
  {
    category: "Indie",
    name: "stardew",
    title: "Stardew Valley",
    publisher: "Chucklefish",
    description: [
      "You've inherited your grandfather's old farm plot in Stardew Valley. Armed with hand-me-down tools and a few coins, you set out to begin your new life. Can you learn to live off the land and turn these overgrown fields into a thriving home? It won't be easy. Ever since Joja Corporation came to town, the old ways of life have all but disappeared. The community center, once the town's most vibrant hub of activity, now lies in shambles. But the valley seems full of opportunity. With a little dedication, you might just be the one to restore Stardew Valley to greatness",
    ],
    info: [
      <h4>Platform: </h4>,
      "iPhone/iPad, PC, PlayStation Vita, Switch, Xbox One",
      <h4>Release Date: </h4>,
      "13 December 2016",
      <h4>Developer: </h4>,
      "Sickhead Games, LLC, Eric Barone",
      <h4>Genre(s): </h4>,
      "Roleplaying, General",
      <h4># of players: </h4>,
      "Up to 5",
      <h4>Rating: </h4>,
      "E",
    ],
  },
  {
    category: "Indie",
    name: "hades",
    title: "HADES",
    publisher: "Superglant Games",
    description: [
      "Defy the god of death as you hack and slash your way out of the Underworld in this rogue-like dungeon crawler from the creators of Bastion and Transistor.",
    ],
    info: [
      <h4>Platform: </h4>,
      "Switch, PC, macOs",
      <h4>Release Date: </h4>,
      "17 September 2020",
      <h4>Developer: </h4>,
      "Superglant Games",
      <h4>Genre(s): </h4>,
      "Action Adventure, General, Linear",
      <h4># of players: </h4>,
      "Singleplayer",
      <h4>Rating: </h4>,
      "T",
    ],
  },
  {
    category: "MMORPG",
    name: "siro",
    title: "Silkroad Online",
    publisher: "Yahoo! Korea",
    home_desc: [
      "Silkroad Online is a historical fantasy MMORPG from Joymax based on the history of China along the famous Silk Road. Reproducing 7th century Silk Road trading while adding fantastic elements, Silkroad Online allows players to create their own characters, complete quests, fight monsters, level up, obtain pets, craft items, engage in PvP, and more.",
    ],
    description: [
      "Silkroad Online is a fantasy MMORPG set in the 7th century AD, along the Silk Road between China and Europe.[2] The game requires no periodic subscription fee, but players can purchase premium items to customize or accelerate gameplay.",
    ],
    info: [
      <h4>Platform: </h4>,
      "PC",
      <h4>Release Date: </h4>,
      "17 October 2005",
      <h4>Developer: </h4>,
      "Joymax",
      <h4>Genre(s): </h4>,
      "Role-Playing, Massively Multiplayer Online, Massively Multiplayer, Fantasy, Fantasy",
      <h4># of players: </h4>,
      "Massive Multiplayer",
      <h4>Rating: </h4>,
      "T",
    ],
  },
  {
    category: "MMORPG",
    name: "wow",
    title: "World of Warcraft",
    publisher: "Blizzard Entertainment",
    description: [
      "Four years have passed since the aftermath of Warcraft III: Reign of Chaos, and a great tension now smolders throughout the ravaged world of Azeroth. As the battle-worn races begin to rebuild their shattered kingdoms, new threats, both ancient and ominous, arise to plague the world once again. World of Warcraft is an online role-playing experience set in the award-winning Warcraft universe. Players assume the roles of Warcraft heroes as they explore, adventure, and quest across a vast world. Being Massively Multiplayer, World of Warcraft allows thousands of players to interact within the same world. Whether adventuring together or fighting against each other in epic battles, players will form friendships, forge alliances, and compete with enemies for power and glory. A dedicated live team will create a constant stream of new adventures to undertake, lands to explore, and monsters to vanquish. This content ensures that the game will never be the same from month to month, and will continue to offer new challenges and adventures for years to come.",
    ],
    info: [
      <h4>Platform: </h4>,
      "PC",
      <h4>Release Date: </h4>,
      "17 October 2005",
      <h4>Developer: </h4>,
      "Blizzard Entertainment",
      <h4>Genre(s): </h4>,
      "Role-Playing, Massively Multiplayer Online, Massively Multiplayer, Fantasy, Fantasy",
      <h4># of players: </h4>,
      "Massive Multiplayer",
      <h4>Rating: </h4>,
      "T",
    ],
  },
  {
    category: "MMORPG",
    name: "knight",
    title: "Knight Online",
    publisher: "MGame",
    description: [
      "Knight Online is officially free-to-play (although to connect to the most of the servers during prime time, paid premium is required), but there are some features that must be paid for. In addition, there is an in-game Powerup Shop or Store which contains various items that one can purchase such as premium packages (freemium model). Paid services include exclusive items and Premiums which are a limited-time subscription providing many benefits.",
    ],
    info: [
      <h4>Platform: </h4>,
      "PC",
      <h4>Release Date: </h4>,
      "17 August 2004",
      <h4>Developer: </h4>,
      "	Mgame Corporation",
      <h4>Genre(s): </h4>,
      "Role-Playing, Massively Multiplayer Online, Massively Multiplayer, Fantasy, Fantasy",
      <h4># of players: </h4>,
      "Massive Multiplayer",
      <h4>Rating: </h4>,
      "T",
    ],
  },
  {
    category: "Racing",
    name: "dirt",
    title: "Dirt 4",
    publisher: "Codemasters",
    home_desc: [
      "Dirt 4 is a racing game focused on rallying. Players compete in timed stage events on tarmac and off-road terrain in varying weather conditions. ... The game features rallycross racing and carries a FIA World Rallycross Championship license.",
    ],
    description: [
      " Dirt 4 puts you at the wheel of the most powerful machines ever made as you face the toughest roads and circuits on the planet in rally, rallycross, and landrush.",
    ],
    info: [
      <h4>Platform: </h4>,
      "PC, PlayStation 4, Xbox One",
      <h4>Release Date: </h4>,
      "8 June 2017",
      <h4>Developer: </h4>,
      "Codemasters",
      <h4>Genre(s): </h4>,
      "Racing, Simulation, Automobile",
      <h4># of players: </h4>,
      "Online Multiplayer",
      <h4>Rating: </h4>,
      "T",
    ],
  },
  {
    category: "Racing",
    name: "forza",
    title: "Forza Horizon 4",
    publisher: "Microsoft Game Studios",
    description: [
      "For the first time in the racing and driving genre, experience dynamic seasons in a shared open-world. Explore beautiful scenery, collect over 450 cars, and become a Horizon Superstar in historic Britain",
    ],
    info: [
      <h4>Platform: </h4>,
      "PC, Xbox One, Xbox Series X",
      <h4>Release Date: </h4>,
      "28 September 2018",
      <h4>Developer: </h4>,
      "Playground Games",
      <h4>Genre(s): </h4>,
      "Racing, Simulation, Automobile",
      <h4># of players: </h4>,
      "Up to 12",
      <h4>Rating: </h4>,
      "E",
    ],
  },
  {
    category: "Racing",
    name: "nfs",
    title: "Need for Speed: Heat",
    publisher: "Electronic Arts",
    description: [
      "Hustle by day and risk it all at night in Need for Speed Heat, a white-knuckle racer that pits you against a city's rogue police force as you battle your way into street racing's elite. By day compete in the Speedhunter Showdown -- a sanctioned competition where you earn bank to customize and upgrade your garage of high-performance cars. When your ride's perfectly styled and hyper-tuned, and you're ready to ramp up the intensity, drive out into the night where you and your crew take on the competition in illicit street races that build your reputation and grant you access to bigger races and better parts. But under the cover of darkness patrols a rogue task force looking to bring you down and swipe all you've earned. Take them on and risk it all for underground glory or head back to your safehouse and begin another thrilling day. The roads, the risks, and the rides never end in this street racer where your crew rolls deep, your garage is full of hot cars, and the city's your nonstop playground.",
    ],
    info: [
      <h4>Platform: </h4>,
      "PC, PlayStation 4, Xbox One",
      <h4>Release Date: </h4>,
      "8 November 2019",
      <h4>Developer: </h4>,
      "Ghost Games",
      <h4>Genre(s): </h4>,
      "Racing, Arcade, Automobile",
      <h4># of players: </h4>,
      "Up to 16",
      <h4>Rating: </h4>,
      "T",
    ],
  },
];
